prisma/seed.ts
src/app/(dashboard)/etudes/[id]/(contributor)/contributeur/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/cadrage/ajouter-contributeur/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/cadrage/ajouter/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/cadrage/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/resultats/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/saisie-des-donnees/[post]/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/saisie-des-donnees/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/page.tsx
src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
src/components/study/rights/NewStudyRightDialog.tsx
src/components/study/rights/NewStudyRightForm.tsx
src/components/study/rights/SelectStudyRole.tsx
src/components/study/rights/StudyRightsTable.tsx
src/db/organization.ts
src/db/study.ts
src/i18n/en.json
src/i18n/fr.json
src/services/permissions/emissionSource.ts
src/services/serverFunctions/emissionSource.ts
src/services/serverFunctions/study.ts
src/services/study.ts
src/tests/end-to-end/app/study-rights.cy.ts

#186  Remplace https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/204
Manque le check sur la licence (pas encore implémentée niveau organisation)
Propositions de changement des messages (mettre en évidence le changement de droit) :
---
- otherOrganization: "They are not within your organization.",
- readerOnly: "If they do not match the necessary conditions for this role, you will only be able to give them access to this study only with READ or contribution rights. An email will be sent to them to give access to the study.",
---
- otherOrganization: "Elle ne fait pas partie de votre organisation."
- readerOnly: "Si elle ne réunit pas les conditions nécessaires pour l'ajouter avec ce rôle, vous ne pourrez donc lui donner un accès qu'à cette étude et avec les droits de LECTURE …

Do not send the non existing user information on add person on study

---

src/app/(dashboard)/organisations/page.tsx
src/db/client.ts
src/db/user.ts
src/services/auth.ts
src/services/serverFunctions/auth.ts

concerns #486 
J'ai pas reussi a faire un truc generalisé  a cause de ca :
"This is a type-safe object that you can mutate before the query happens. You can mutate any of the properties in args. Exception: you cannot mutate include or select because that would change the expected output type and break type safety."
du coup j'ai du multiplié les champs. Quid de ce qui se passe si tu fais un createAndReturn ? normalement c'est ok, vu que si tu crées c'est que tu as deja l'info.
On ne peut pas faire de delete non plus vu que password est fortement typé, donc si tu le demande pas tu dois le retourner quand même. D'ou le  = ''
Je trouve ce code un peu lourd, mais je ne vois pas comment faire autrement. Du coup ma reco c'est de ne pas le merger et de continuer de faire attention à ce qu'on …

chore: protect password

---

src/db/emissionFactors.ts

related to #536 
On ne veut pas récupérer les FEs qui ne sont pas attribués à un sous poste. J'ai laissé la possibilité si la personne le récupère directement via l'id, je me suis dit que si il avait l'id c'est qu'il y avait probablement une raison (FE qui était utilisé avant dans une étude car il fut attribué par exemple mais ne l'est plus)

only get emission factor with subpost

---

src/css/globals.css

Je sais pas trop pourquoi sur figma c'est amrqué qu'on est seulement à 400 de font weight alors que clairement on est à plus. je me demande si c'est pas parce que c'est 400 par rapport à Gilroy semi bold ? 
Dans tous les cas c'est plus proche de la maquette ainsi.

increase boldness

---

src/components/organization/Organization.module.css

#494 (cf comment https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/494#issuecomment-2670812831)
Corrige uniquement la couleur de fond des cartes des clients d'un utilisateur CR. Les autres points seront corrigés à l'avenir s'il le faut

fix client card background color

---

src/services/serverFunctions/organization.ts

Si l'utilisateur n'était pas dans l'orga ca le mettait en validated alors que du coup il faut qu'il ne soit pas pris en compte. 
Bug pas hyper grave car ne l'ajoute pas à l'orga mais le met en validé donc pas fou (et cas peu probable en +)

fix onboarding for user not in orga

---

src/services/importEmissionFactor/baseEmpreinte/getEmissionFactorsFromAPI.ts
src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
src/services/importEmissionFactor/import.ts

bug sur staging avec des bilan aux résultats doublés : plusieurs imports ont été réalisés avec les même facteurs d'émissions, mélangeant les composantes des FE. Ce qui fait que certaines lignes des exports beges avaient des valeurs doublées

fetch emission factors from current import

---

src/components/organizationCard/OrganizationCard.tsx
src/css/globals.css
src/css/index.css

https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/755
Dans la foulée J'ai aussi résolu le problème en prod avec les différences de style notamment sur les h1 ! En fait je pense que le fait de charger la font dans global faisait recharger le reset.css donc je l'ai mis avant tous les imports si ça vous va

bug/755 removing flex-end for better icon alignement with methodo button

---

prisma/legacy_data/actualities.ts
src/components/actuality/Actuality.tsx

Fix suite à une erreur détectée avec l'utilisation de DOMPurify : 
Solution trouvée ici (je n'ai pas réussi à sécuriser les données à l'enregistrement. Dans tous les cas, je pense que c'est une bonne chose de faire un nettoyage côté front) : https://www.reddit.com/r/nextjs/comments/kty9vi/comment/giptplq/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

fix dompurify import usage

---

src/db/emissionFactors.ts

#822 
Le problème venait du fait que l'on ne récupère pas versionId des FE, et donc on ne peut pas filtrer sur versionId, mais il est possible de le faire sur version.id
Pour reproduire le bug en local, il faut simplement ne pas avoir de NO_CACHE=true dans son .env

fix getCachedDefaultEmissionFactors function for study

---

src/db/user.ts

bug en production : les utilisateurs importés n'ont pas l'étape "CreateAccount" validée (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/475#issuecomment-2758522452)

fix createAccount step validation

---

src/components/emissionFactor/Form/MultiplePosts.tsx
src/components/emissionFactor/Form/Posts.tsx
src/components/emissionFactor/Table.tsx
src/components/study/rights/NewStudyContributorForm.tsx

https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/754
Corrections suite à https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/870
J'ai laissé au maximum Post pour tout l'aspect logique mais j'ai utilisé BCPost qui contient seulement les posts du BC pour les endroits ou ils étaient affiché (normalement ce sont des endroits exclusif BC pour l'instant à voir si il faut complexifier par la suite)

fix: 754 BCPost instead of Post for special cases in BC

---

package.json

tsx instead of ts-node
To correct error of heap memory because of node version 22

tsx instead of ts-node

---

src/components/study/results/AllResults.tsx
src/services/posts.ts
src/services/results/consolidated.ts
src/services/study.ts

Fix d'un bug suite à la PR https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/870
Par défaut on utilise toujours que les postes BC et on verra côté cut etc... ce qu'on veut utiliser
@cmolle je te laisse check :)

fix: fixing bug export bcposts

---

src/scripts/oldBC/transition/oldBC.ts
src/scripts/oldBC/transition/organizations.ts

Avant, on ne créait pas ce site par défaut, et donc il y avait des cas où on ne pouvait rajouter ni les études, ni les sites des études, ni les données sources qui y étaient fonctionnellement rattachées.

Create default site for user organization

---

src/services/serverFunctions/study.ts

#666 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/666#issuecomment-2827973987)
Question : On n'ajoute pas le contributeur si la personne a déjà accès à l'étude : On vérifie son rôle via la fonction `getUserRoleOnStudy` mais qu'en est-il si la personne a le rôle `Reader` ? En soit, un contributeur a plus de droits d'édition qu'un lecteur

fix add contributor check when user has a default role

---

src/services/serverFunctions/user.ts

#930 
ajout de la source lors de la création d'un utilisateur. Pour l'instant on met la meme source que l'utilisateur qui créé. A vori plus tard si on veut pas mieux gérer ca. 
Je n'ai pas fait la remise à 0 de la formation car ils n'ont plus accès à la page si ils sont pas de la source CRON

add source

---

src/components/onboarding/OnboardingModal.tsx

#695
Vu ensemble : on oubli le problème de validation du formulaire (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/695#issuecomment-2857503080). En revanche, ça a mis en évidence 2 autres soucis :
- Le bouton "précédent" est disponible dès l'étape 1
- Si on ajoute un email invalide lors de l'étape 2 et qu'on revient à l'étape 1, on ne peut plus valider pour retourner à l'étape 2

fix onbording form when go to previous step with invalid form

---

src/app/(dashboard)/layout.tsx
src/components/study/perimeter/StudyPerimeter.tsx
src/utils/organization.ts

3 bugs détectés sur master. Un hotfix est en cours de déploiement, mais je répercute les changements sur develop : 
- Un contributeur invité, normalement sans organisation a sa page d'accueil en erreur car le bouton de checklist a besoin de organisationId
- Ce même contributeur a accès aux études avec les droits lecteur car le test canReadStudyDetail n'est pas parfait :
- Le test `(study.isPublic &&
isInOrgaOrParent(user.organizationVersionId, study.organizationVersion as OrganizationVersionWithOrganization))` peut passer car user.organizationVersionId est null et dans certains cas, organizationVersion.parentId est null également
- Un utilisateur avec le rôle lecteur a accès aux champs export en édition

fix organizationLess contributors access

---

prisma/schema/migrations/20250519130837_create_account_and_organization_version_tables/migration.sql
prisma/schema/migrations/20250519134457_remove_old_user_and_organization_field_for_account_and_organization_version_refactor/migration.sql

Ca ne change rien en local mais ça permet de fixer une erreur de migrations qu'il y avait avec la branche https://github.com/ABC-TransitionBasCarbone/bilan-carbone/tree/MIGRATE_AND_SCRIPT_BEFORE_ACCOUNT
Il manquait le "?" sur uploader de accountId dans document sur la première PR

fix: fixing bad migrations for account/user deployment

---

src/components/study/organization/Select.tsx
src/tests/end-to-end/app/create-emission-source.cy.ts
src/tests/end-to-end/app/create-study.cy.ts

Le test `should create a study on your organization as a simple user` était en erreur sur la CI depuis le merge de la PR https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/1078 (pour aucune raison apparente, pas de problème en local). Les screenshots semblent indiquer que le sélecteur de sites pour l'étude s'est rechargé après la sélection du site de l'étude, mais avant le clic sur la validation. J'ai cherché d'où pouvait venir ce re-render et pense l'avoir corrigé

fix study creation re-rendering

---

prisma/seed/index.ts
prisma/seed/utils.ts
src/app/(dashboard)/equipe/ajouter/page.tsx
src/components/pages/NewMember.tsx
src/components/pages/Team.tsx
src/components/team/InvitationsToValidate.tsx
src/components/team/InvitationsToValidateActions.tsx
src/components/team/NewMemberForm.tsx
src/components/team/PendingInvitations.tsx
src/components/team/SelectRole.tsx
src/components/team/TeamTable.tsx
src/i18n/fr-cut.json
src/services/permissions/user.test.ts
src/services/permissions/user.ts
src/services/roles.ts
src/services/serverFunctions/user.ts
src/tests/end-to-end/app/team.cy.ts
src/utils/organization.ts
src/utils/study.ts
src/utils/user.test.ts
src/utils/user.ts

Link to #881 
Je pense que ce serait bien que cette PR soit relu par 1 personne côté CUT + @fortinlouis 
PR à tester
Ce que je n'ai pas géré dans cette PR car je suppose que ce sera fait ailleurs @RomainCrevecoeur 
- Modale d'onboarding 
- Checklist
- L'ajout d'un utilisateur dans une étude (à priori géré par la PR de @jilink)
Choix tech : 
Les validations zod sont plus larges que ce que l'on devrait accepter niveau role pour CUT. Cependnat je n'ai pas trouvé de manière simple de faire autrement vu que notre type est défini via zod et donc impossible de savoir l'environnement.
Question : 
Il n'y a pas besoin d'une traduction de cut en anglais ? Est-ce que c'est bien prévu de bloquer la possibilité ? @RomainCrevecoeur 
J'ai une erreur de lint sur fr-cut mais j'ai toujours un problème en …

change role for cut

---

src/components/study/card/StudyCard.module.css
src/components/study/card/StudyCard.tsx
src/components/study/card/StudyPostsCard.module.css
src/components/study/card/StudyPostsCard.tsx

correction du bug de couleur sur staging quand la progress bar est complète. Suite à de nombreux échecs, j'ai tenté des correctifs que j'ai déployé en live sur staging pour être sûr du résultat (ça marchait aussi avec un yarn build + yarn start) :

fix progress bar success color

---

src/scripts/ftp/userImport.ts

- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1179
J'utilise la fonction pour déterminer le bon rôle des users cut quand ils sont importés du cron sinon c'est toujours collaborator pour les autres

fix: fix cut users from cron have default role and not collaborator

---

src/environments/cut/layout/Footer.module.css
src/environments/cut/layout/Footer.tsx
src/i18n/en.json
src/i18n/fr-cut.json
src/i18n/fr.json

- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1023
J'ai passé la witdh à 100% au lieu de 100vw car sinon bizarrement ça prenait un peu plus que la largeur et y avait une scrollbar en bas (probablement l'espace blanc dont parlait Gabriel dans le ticket)

fix: typo footer + removing horizontal scrollbar

---

src/scripts/cut/question/utils.ts

L’utilisation de script d’import, si dans le fichier `CSV`, un champ de la colonne `Unité` est vide, le `Parser` le voit comme une chaîne vide. Ce qui ne fait pas partie de l’enum prisma.
Ajouter une condition si `unit` est une chaîne vide alors renvoyer `null` sinon renvoyer `unit`
- #1323

Une `Unite` peut être une chaîne vide

---

package.json
src/scripts/cut/question/utils.ts
src/services/unit.ts

Lors de l’importations des questions dans l’environnements `CUT`, nous voulons que l’unité `KEURO` soit disponible
- Déplacer l’unité souhaité de `BCUnit` à `CommonUnit` permettant l’utilisation de `KEURO` dans les deux environnements
- De plus, lors de l’import mettre l’unité reçu du fichier (excel ou csv) en majuscule pour contrer les potentiels erreurs humaines.
- Ajouter une commande dans le `package.json` pour simplifier l’import des questions
- #1437

L’unité `KEURO` n’est pas géré pour CUT 

---

src/components/study/perimeter/flow/StudyFlow.tsx
src/i18n/en.json
src/i18n/fr.json
src/services/permissions/environment.ts
src/services/permissions/study.ts
src/services/serverFunctions/studyFlow.ts

- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1455
Je n'ai pas vraiment pu tester en local si le bouton de téléchargement fonctionne car je pense que scaleway ne m'y autorise pas
J'ai ajouté une variable d'environnement avec la clef du fichier d'exemple, dites moi si c'est ok pour vous, voilà la clef à mettre sur staging :
`STUDY_FLOW_EXAMPLE_KEY=dd3e3d12-d875-4418-85a7-9f33b6eecfad`

feat: tilt sample button for studyFlow

---

src/db/user.ts
src/services/serverFunctions/user.ts

https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1577
Tant que ça n'a pas été mergé, ne pas utiliser les deactivable feature sur la création de compte en prod/staging

fix: fixing deactivable feature bug on user creation from tilt/cut

---

src/components/study/EmissionSourceFactor.tsx
src/services/emissionSource.ts

lié à #811 @fortinlouis c'est normal qu'il n'y ait rien dans achats de service (c'est un sous poste pour les utilisateurs mais ils doivent y ajouter leurs FE) parcontre y avait bien un autre bug (on ne pouvait pas voir les FEs qui n'étaient pas ceux du sous poste de base) que j'ai corrigé 
Lié  à #1118

Multiple fixes fe posts and beges
