ABC-TransitionBasCarbone/bilan-carbone

- package.json
- prisma/migrations/20241010084006_add_license/migration.sql
- prisma/schema/actuality.prisma
- prisma/schema/license.prisma
- prisma/schema/schema.prisma
- prisma/seed.ts
- yarn.lock
> feat: add licenses

- prisma/migrations/20241010085729_add_actuality_timestamp/migration.sql
- prisma/schema/actuality.prisma
> feat: add timestamp in actuality

- package.json
- prisma/migrations/20241017133708_add_emissions/migration.sql
- prisma/schema/emission.prisma
- src/scripts/getEmissionsFromEmpreinte.ts
- tsconfig.json
- yarn.lock
concern #23 
Attention : pas de mecanisme d'archive pour linstant
> feat: add FE table and import them from BE

- cypress/support/commands.ts
- cypress/support/cypress.d.ts
- prisma/migrations/20241022103828_add_emission_organization/migration.sql
- prisma/schema/emission.prisma
- prisma/schema/organization.prisma
- prisma/seed.ts
- src/app/(dashboard)/facteurs-d-emission/creer/page.tsx
- src/components/base/Form.module.css
- src/components/base/Form.tsx
- src/components/emission/Table.module.css
- src/components/emission/Table.tsx
- src/components/emission/new/Form.tsx
- src/components/form/TextField.tsx
- src/components/pages/NewEmission.tsx
- src/components/study/new/Form.module.css
- src/components/study/new/Form.tsx
- src/db/emissions.ts
- src/i18n/fr.json
- src/services/auth.ts
- src/services/emissions.ts
- src/services/serverFunctions/emission.command.ts
- src/services/serverFunctions/emission.ts
- src/tests/end-to-end/app/auth.cy.ts
- src/tests/end-to-end/app/create-emission.cy.ts
- src/tests/end-to-end/app/create-study.cy.ts
- src/tests/end-to-end/app/home.cy.ts
- src/tests/end-to-end/app/legal-notices.cy.ts
- src/types/next-auth.d.ts
> feat: allow user to add FE

- src/scripts/getEmissionsFromEmpreinte.ts
Too many connections at once when saving posts in prod
> fix: use less connection when importing FE

- src/app/(dashboard)/profil/page.tsx
- src/components/base/Link.module.css
- src/components/base/Link.tsx
- src/components/study/PostInfography.module.css
- src/components/study/PostInfography.tsx
- src/components/study/PostsInfography.module.css
- src/components/study/PostsInfography.tsx
- src/components/study/Studies.module.css
- src/components/study/Studies.tsx
- src/components/study/StudyDetails.tsx
- src/components/study/new/Form.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.ts
- src/tests/end-to-end/app/create-study.cy.ts
- src/tests/end-to-end/app/study-rights.cy.ts
Note: il n'y a pas les boutons "Vers la ..."
j'ai encore du mal a voir a quoi ca va ressembler donc je laisse ca en suspens (et en gros la page actuelle correspond à celle de la comptabilisation)
Et c'est pas tres responsive... (discussion en cours)
> feat: Add post infography to study

- .github/workflows/ci.yml
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/88
cf doc : https://github.blog/changelog/2023-12-14-github-actions-artifacts-v4-is-now-generally-available/
> update artifacts version

- src/app/(dashboard)/etudes/[id]/droits/ajouter/page.tsx
- src/components/form/Autocomplete.module.css
- src/components/form/Autocomplete.tsx
- src/components/pages/NewStudyRight.tsx
- src/components/study/rights/NewStudyRightForm.module.css
- src/components/study/rights/NewStudyRightForm.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.command.ts
- src/tests/end-to-end/app/study-rights.cy.ts
#102
Ajout d'un auto-complete
message d'avertissement si l'utilisateur n'est pas dans l'organisation ou n'a pas de compte
Pas d'utilisation du nom/prenom -> création d'un nouveau ticket : #106
> change new study user from TextField to AutoComplete field

- prisma/migrations/20241114155959_add_contributors/migration.sql
- prisma/schema/study.prisma
- prisma/schema/user.prisma
- src/app/(dashboard)/etudes/[id]/droits/ajouter-contributeur/page.tsx
- src/components/pages/NewStudyContributor.tsx
- src/components/pages/StudyRights.tsx
- src/components/study/rights/NewStudyContributorForm.tsx
- src/components/study/rights/StudyContributorsTable.tsx
- src/components/study/rights/StudyRightsTable.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/permissions/study.ts
- src/services/serverFunctions/study.command.ts
- src/services/serverFunctions/study.ts
Ajout des contributeurs depuis la page de droits
RAF => 
la date butoire
la mention des contributeurs dans les pages de sources
un test e2e globale
> feat: Add contributors on study rights

- prisma/migrations/20241118133229_remove_contribution_date/migration.sql
- prisma/schema/study.prisma
- prisma/seed.ts
- src/components/study/rights/NewStudyContributorForm.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/emissionSource.test.ts
- src/services/serverFunctions/study.command.ts
> feat: Remove limit contribution date

- src/components/form/Autocomplete.tsx
- src/components/pages/NewStudyRight.tsx
- src/components/study/rights/NewStudyRightForm.tsx
- src/db/organization.ts
> add the possibility to filter on user firstname - lastname

- src/app/(dashboard)/etudes/[id]/perimetre/page.tsx
- src/components/pages/StudyPerimeter.tsx
- src/components/study/perimeter/StudyPerimeter.module.css
- src/components/study/perimeter/StudyPerimeter.tsx
- src/db/organization.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/permissions/study.ts
- src/services/serverFunctions/study.command.ts
- src/services/serverFunctions/study.ts
> feat: add study perimeter page

- prisma/migrations/20241122110304_optional_user_info/migration.sql
- prisma/schema/user.prisma
- prisma/seed.ts
- src/app/(dashboard)/etudes/creer/page.tsx
- src/app/(dashboard)/organisations/[id]/page.tsx
- src/components/pages/NewStudyRight.tsx
- src/components/study/rights/NewStudyRightDialog.tsx
- src/components/study/rights/NewStudyRightForm.tsx
- src/components/study/rights/SelectStudyRole.tsx
- src/components/study/rights/StudyLevel.tsx
- src/components/study/rights/StudyPublicStatus.tsx
- src/components/study/rights/StudyRightsTable.tsx
- src/db/organization.ts
- src/db/study.ts
- src/db/user.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/emissionFactors.ts
- src/services/permissions/organization.ts
- src/services/permissions/study.ts
- src/services/permissions/user.ts
- src/services/serverFunctions/emissionFactor.ts
- src/services/serverFunctions/organization.ts
- src/services/serverFunctions/study.ts
- src/services/serverFunctions/user.ts
- src/services/study.ts
- src/tests/end-to-end/app/study-rights.cy.ts
> feat: manage invitation from other organization

- src/components/study/EmissionSource.module.css
- src/components/study/EmissionSource.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/emissionSource.ts
concerns #65 
Ajout d'une info comme quoi la sauvegarde est en cours
Suppression des sauvegardes inutiles
Alert si jamais qqch se passe mal (par exemple, pas les droits) :
> feat: add info on saving emission source

- src/app/(dashboard)/etudes/[id]/comptabilisation/resultats/page.tsx
- src/components/pages/Results.tsx
- src/components/study/results/ResultsTable.module.css
- src/components/study/results/ResultsTable.tsx
- src/css/reset.css
- src/i18n/fr.json
- src/services/emissionSource.test.ts
- src/services/emissionSource.ts
- src/services/uncertainty.ts
- src/tests/end-to-end/app/create-emission-source.cy.ts
concers #112 
* Gestion des résultats de base
* Affichage de tous les postes, et uniquement les sous postes avec valeurs
* Manque la partie par sites qu'on n'a pas pour l'instant
> feat: display study results

- src/components/emissionFactor/Table.module.css
- src/components/emissionFactor/Table.tsx
- src/i18n/fr.json
- src/tests/end-to-end/app/create-emission-factor.cy.ts
concerns #168 
Juste la simplification de la ligne
RAF les infos au click
> feat: simplify emission factor table

- src/components/study/DeleteEmissionSource.tsx
- src/components/study/EmissionSource.module.css
- src/components/study/EmissionSourceForm.tsx
- src/components/study/rights/NewStudyRightDialog.tsx
- src/db/emissionSource.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/permissions/emissionSource.ts
- src/services/serverFunctions/emissionSource.ts
- src/tests/end-to-end/app/delete-emission-source.cy.ts
> feat: Allow user to delete emission source

- prisma/migrations/20241203134412_add_export_rule/migration.sql
- prisma/schema/emissionFactor.prisma
- prisma/schema/study.prisma
- src/components/emissionFactor/new/Form.tsx
- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceForm.tsx
- src/components/study/NewEmissionSource.tsx
- src/components/study/SubPost.tsx
- src/services/baseEmpreinte/getEmissionFactors.ts
- src/services/emissionSource.ts
- src/services/serverFunctions/emissionFactor.command.ts
- src/services/serverFunctions/emissionSource.command.ts
- src/services/serverFunctions/emissionSource.ts
- src/tests/end-to-end/app/create-emission-factor.cy.ts
- src/tests/end-to-end/app/create-emission-source.cy.ts
first part of #113 
note: c'est une PR partielle car tres imbriqué avec la suite et j'ai pas envie de faire une PR de 5k lignes
du coup il y a des trucs manquant (genre les traductions)
et des trucs en plus (genre la config beges)
> feat: add caracterisation on Emission source

- src/components/study/results/beges/BegesResultsTable.tsx
- src/services/exportRules/beges.config.ts
- src/services/results/beges.ts
finish #113 
Toutes ces méthodes ne sont pas testées.. et du coup possiblement (probalement) fausses
en attente du vraie use case pour corriger tout ca
> feat: proper ventilation in beges export

- src/components/study/DeleteEmissionSource.tsx
- src/components/study/EmissionSourceForm.tsx
> feat: review delete emission source button

- prisma/migrations/20241206103021_add_site_on_study/migration.sql
- prisma/schema/organization.prisma
- prisma/schema/study.prisma
- prisma/seed.ts
- src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
- src/components/form/Checkbox.tsx
- src/components/pages/NewStudy.tsx
- src/components/pages/StudyPerimeter.tsx
- src/components/study/new/Form.tsx
- src/components/study/organization/Select.tsx
- src/components/study/organization/Sites.module.css
- src/components/study/organization/Sites.tsx
- src/components/study/perimeter/StudyPerimeter.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.command.ts
- src/services/serverFunctions/study.ts
- src/tests/end-to-end/app/create-study.cy.ts
- src/tests/end-to-end/app/study-rights.cy.ts
concerns #157 
Concerne le choix des sites à la création de l'étude et l'affichage dnas la partie perimetre
RAF: 
* la modification
* les selecteurs
> feat: Manage site on study level

- src/services/baseEmpreinte/import.ts
> add Incertitude to fetched columns in API call

- src/components/pages/StudyRights.tsx
- src/components/study/rights/StudyPublicStatus.tsx
- src/components/study/rights/StudyRightsTable.tsx
- src/i18n/en.json
- src/i18n/fr.json
Prise en compte du retour de Gabriel sur l'ajout d'une section pour la gestion des utilisateur. j'en ai profité pour bouger le bouton de place pour qu'il soit au niveau du tableau et non pas au niveau global de la page
> fix on cadrage page

- src/tests/end-to-end/app/study-rights.cy.ts
- Suppression des 2 tests d'édition de rôle
- Ajout d'autres cas pour garder les autres tests pertinents
> comment flaky test and adapt other

- src/components/study/EmissionSource.module.css
- src/components/study/EmissionSource.tsx
- src/tests/end-to-end/app/create-emission-source.cy.ts
> fix: display activity data in emission source summary

- src/components/emissionFactor/Table.module.css
- src/components/emissionFactor/Table.tsx
- src/components/pages/StudyContribution.tsx
- src/components/pages/StudyContributor.tsx
- src/components/pages/StudyPosts.tsx
- src/components/study/NewEmissionSource.tsx
- src/components/study/SubPost.tsx
- src/components/study/SubPosts.tsx
- src/components/study/buttons/StudyPostsBlock.tsx
- src/components/study/infography/AllPostsInfography.tsx
- src/components/study/site/SelectStudySite.tsx
- src/components/study/site/useStudySite.ts
- src/services/permissions/study.ts
- src/services/study.ts
> fix: only display sites emission sources

- prisma/migrations/20241220154147_rename_study_sites_and_user_id/migration.sql
- prisma/schema/study.prisma
> chore: rename table and column in snake_case

- src/components/study/new/ExportCheckbox.tsx
> fix: use operational controle mode by default

- prisma/migrations/20241223154754_old_bc_id/migration.sql
- prisma/schema/emissionFactor.prisma
> chore: add old BC Id on emission factors

- src/components/base/Box.module.css
- src/components/breadcrumbs/Breadcrumbs.module.css
- src/components/study/EmissionSourceFactor.module.css
- src/components/study/infography/AllPostsInfography.module.css
- src/components/study/infography/AllPostsInfography.tsx
- src/components/studyNavbar/StudyNavbar.module.css
- src/css/globals.css
- src/css/variables.css
> feat: review colors

- src/components/study/EmissionSourceForm.tsx
- src/services/results/beges.ts
> fix: Mandatory contribution

- prisma/migrations/20241223130818_add_depreciation_period/migration.sql
- prisma/schema/study.prisma
- prisma/seed/study.ts
- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceContributorForm.tsx
- src/components/study/EmissionSourceForm.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/emissionSource.ts
- src/services/permissions/emissionSource.ts
- src/services/permissions/study.ts
- src/services/results/beges.ts
- src/services/results/consolidated.ts
- src/services/serverFunctions/emissionSource.command.ts
concerns #252 
Discussion en cours sur ou stocker le depreciationPeriod, pour l'instant, au plus simple
> feat: add immobilisation depreciation period

- package.json
- src/app/(dashboard)/transition/page.tsx
- src/components/navbar/Navbar.module.css
- src/components/navbar/Navbar.tsx
- src/components/pages/TransitionPage.tsx
- src/components/study/perimeter/flow/StudyFlow.module.css
- src/components/study/perimeter/flow/StudyFlow.tsx
- src/components/transition/Organizations.module.css
- src/components/transition/Organizations.tsx
- src/css/variables.css
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/transitions.ts
- yarn.lock
concerns #201 
RAF : que faire des ids non existants (exemple: 110 587d5a9c-a83c-4d5d-bb2a-35a45c4f4846 TEST - CHLOÉ Test à supprimer 0
d56712ae-52c2-4251-b16b-dc82645d99140)
Attention, il y a pleins de use case chelou pour gerer le multiple import. A bien tester avec des vrais données
> feat: allow user to download old organizations

- prisma/migrations/20241219181140_add_legifrance_import_value/migration.sql
- prisma/schema/emissionFactor.prisma
- src/components/emissionFactor/Table.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/scripts/legifrance/getEmissionFactors.ts
- src/services/importEmissionFactor/import.ts
- src/services/importEmissionFactor/legifrance/getEmissionFactors.ts
#254 suite à la PR https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/306 que j'ai fermé pour éviter tous les conflits
> add import emission factors from legifrance csv

- src/app/(dashboard)/organisations/[id]/etudes/creer/page.tsx
- src/components/pages/NewStudy.tsx
- src/components/study/StudiesContainer.tsx
> fix: use default organisation on study

- src/services/results/consolidated.ts
> fix: infographie show unvalidated emission source

- cron.json
- package.json
- src/scripts/ftp/importUsers.ts
linked to https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/199
> add cron to scalingo

- src/app/error.tsx
- src/app/not-found.tsx
- src/components/pages/Error.tsx
- src/i18n/en.json
- src/i18n/fr.json
Lié à https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/278
To improve
> add global error page

- src/components/study/EmissionSourceFactor.module.css
- src/components/study/EmissionSourceFactor.tsx
- src/components/study/EmissionSourceFactorDialog.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/utils/string.ts
> 281 ameliorate fe selection

- src/components/study/EmissionSourceForm.tsx
- src/i18n/en.json
- src/i18n/fr.json
Supprimer les valeurs négative pour les données d'activité
> remove negative value 

- prisma/seed/study.ts
> fix: Add validator on BCv8.10

- src/components/study/EmissionSourceForm.tsx
link to https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/280
> error disapear

- src/app/(dashboard)/profil/page.tsx
- src/components/pages/Profile.tsx
- src/components/profile/Profile.module.css
- src/components/profile/Profile.tsx
- src/css/flex.css
- src/db/user.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/auth.ts
- src/services/serverFunctions/user.command.ts
- src/services/serverFunctions/user.ts
> display user name and add edition option in profile

- src/components/study/new/ExportCheckbox.tsx
- src/components/study/results/AllResults.tsx
- src/db/study.ts
> disable financial and capitalShare beges exports

- src/components/study/results/AllResults.tsx
- src/services/file.ts
- src/services/serverFunctions/file.ts
- src/services/serverFunctions/study.ts
- src/services/study.ts
> 302 export results

- src/services/serverFunctions/transitions.ts
> fix: Manage deleted organization in old BC organization import

- .env.dist
- src/db/emissionFactors.ts
- src/services/emissionFactors.ts
- src/services/utils.ts
- src/tests/end-to-end/app/create-emission-factor.cy.ts
concerns #269 
Server has to be restart when manually uploading FE
NO_CACHE used locally and in CI to avoid issue with seeds
> chore: cache FE

- src/components/organization/edit/EditOrganizationForm.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.ts
> prevent organization site deletion when used on studies

- src/components/organization/edit/EditOrganizationForm.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.ts
#353 (relatif commentaire https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/353#issuecomment-2589424161)
> do not send link of unauthorized studies

- src/components/organization/Sites.tsx
- src/components/organization/edit/EditOrganizationForm.tsx
- src/components/pages/NewStudy.tsx
- src/components/study/organization/Select.tsx
- src/db/organization.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.ts
> feat: update ca in keuros

- src/services/results/beges.ts
> fix: compute beges even without uncertainty

- eslint.config.mjs
- src/components/study/new/ExportCheckbox.tsx
- src/components/study/results/AllResults.tsx
- src/components/studyNavbar/StudyNavbar.tsx
- src/i18n/en.json
- src/i18n/fr.json
> feat: display comming to other exports

- src/components/auth/Auth.module.css
- src/components/auth/ResetForm.tsx
- src/css/variables.css
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/auth.ts
- src/services/utils.ts
- src/tests/end-to-end/app/auth.cy.ts
- src/tests/end-to-end/app/team.cy.ts
> feat: add proper reset password informations

- src/components/emissionFactor/new/DetailedGES.tsx
> fix: recompute total in new FE

- src/i18n/en.json
- src/i18n/fr.json
> feat: explicit  tCO₂e in beges results

- src/components/emissionFactor/new/Form.tsx
> fix: Validation of FE creation form

- src/components/home/UserView.tsx
- src/components/pages/Organization.tsx
- src/components/study/results/ResultsContainerForUser.tsx
- src/db/study.ts
> fix: Show graph for allowed organizations

- src/components/form/QualitySelect.tsx
- src/components/study/EmissionSource.module.css
- src/components/study/QualitySelectGroup.tsx
> fix: Quality size in emission source form

- src/components/auth/ResetForm.tsx
> fix: Block reset password if not matching

- src/components/base/Block.tsx
- src/components/base/LoadingButton.tsx
- src/components/study/SubPost.tsx
- src/components/study/buttons/StudyPostsBlock.tsx
- src/components/study/results/Result.tsx
> add loader on downloading buttons

- src/components/study/results/ResultsContainerForUser.tsx
> fix: await results of canreadstudy

- src/components/study/site/useStudySite.ts
#265 correction du bug du site sélectionné par défaut quand ce dernier a été supprimé
> fix default studySite after removal

- src/components/study/infography/PostHeader.module.css
- src/components/study/infography/PostHeader.tsx
- src/components/study/infography/PostInfography.tsx
> fix: post background in ff

- src/components/study/organization/Select.tsx
- src/i18n/en.json
- src/i18n/fr.json
> fix: display error when ca or etp is negative

- src/components/emissionFactor/new/DetailedGES.tsx
- src/components/emissionFactor/new/Form.tsx
- src/constants/emissions.ts
- src/services/serverFunctions/emissionFactor.command.ts
Pas tres content du z.nan() dans la validation :/
Si qqun a une idée je suis preneur.
concerns #422
> feat: manage suppression of value in EF creation

- src/components/pages/NewStudy.tsx
- src/components/pages/NewStudyContributor.tsx
- src/components/pages/NewStudyRight.tsx
- src/components/pages/Organization.tsx
- src/components/pages/Results.tsx
- src/components/pages/Study.tsx
- src/components/pages/StudyContribution.tsx
- src/components/pages/StudyPerimeter.tsx
- src/components/pages/StudyPosts.tsx
- src/components/pages/StudyRights.tsx
- src/db/study.ts
> feat: add organization name in breadcrumb

- src/components/study/organization/Select.tsx
> fix: Missing etp and ca in validation

- src/components/pages/NewStudy.tsx
- src/components/pages/NewStudyContributor.tsx
- src/components/pages/NewStudyRight.tsx
- src/components/pages/Results.tsx
- src/components/pages/Study.tsx
- src/components/pages/StudyContribution.tsx
- src/components/pages/StudyPerimeter.tsx
- src/components/pages/StudyPosts.tsx
- src/components/pages/StudyRights.tsx
> fix: typo on organisations link

- src/components/study/EmissionSourceForm.tsx
> fix: compute value in cas

- src/components/emissionFactor/edit/EditEmissionFactorModal.tsx
#359 (relatif au commentaire https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/359#issuecomment-2621776142)
> add loading button

- src/scripts/actuality/add.ts
- src/scripts/actuality/delete.ts
- src/services/importEmissionFactor/getEmissionFactorsFromCSV.ts
- src/utils/csv.ts
> feat: Add script to manage actualities

- src/components/emissionFactor/edit/EditEmissionFactorModal.tsx
#359 (cf comment https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/359#issuecomment-2630437613)
> await end of deletion before closing modale

- src/i18n/en.json
- src/i18n/fr.json
- src/tests/end-to-end/app/delete-study.cy.ts
#315 (cf comment https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/315#issuecomment-2630440626)
> update error label

- src/services/results/consolidated.ts
#374 (cf commentaire https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/374#issuecomment-2640342347)
> fix validatedEmissionSourceOnly usage in computeResultsByPost function

- src/components/study/EmissionSource.tsx
- src/services/permissions/emissionSource.ts
> admin can validate emission source

- src/i18n/en.json
- src/i18n/fr.json
- src/services/email/email.ts
- src/services/email/views/activate-account.ejs
- src/services/email/views/new-user.ejs
- src/services/email/views/reset-password.ejs
- src/services/serverFunctions/user.ts
> add new user email

- src/components/emissionFactor/edit/EditEmissionFactorModal.tsx
- src/components/modals/Modal.tsx
- src/components/organization/edit/EditOrganizationForm.tsx
- src/components/study/DeleteEmissionSource.tsx
- src/components/study/StudyDetailsHeader.tsx
- src/components/study/perimeter/DeleteStudySites.tsx
- src/components/study/rights/NewStudyRightModal.tsx
- src/css/globals.css
- src/css/variables.css
- src/i18n/en.json
- src/i18n/fr.json
- src/utils/components.tsx
> add red color on warning

- src/app/(public)/reset-password/page.tsx
- src/components/auth/ActivationForm.tsx
- src/services/serverFunctions/auth.ts
- src/services/serverFunctions/user.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/545
Fonctionnement actuel
```mermaid
sequenceDiagram
participant A as Adhérent<br/>(isValidated:false, <br/>isActivated:false)
participant AV as AdhérentValide<br/>n'a pas validé son compte dans le temps imparti<br/>(isValidated:true, <br/>isActivated:false)
participant UnA as UtilisateurNonAdhérent<br/>(isValidated:true, <br/>isActivated:false)
participant U as Utilisateur<br/>(isValidated:true, <br/>isActivated:true)
participant ACT as Activation<br/>(isValidated:true, <br/>isActivated:true)
A-->ACT: Activation
A->>ACT: Demande à activer son compte
ACT->>A: Vous avez bien un compte non actif et non validé voici le mail d'activation
A->>ACT: Clique sur le lien d'activation > Activation
AV->>ACT: Demande à activer son compte …
```
> check user is validated to authorize password change

- .env.dist
- src/components/study/rights/StudyContributorsTable.tsx
- src/components/study/rights/StudyRightsTable.tsx
- src/css/globals.css
- src/i18n/en.json
- src/i18n/fr.json
#511 (cf commentaire https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/511#issuecomment-2665043641)
> fix infobulle content from cadrage page

- src/components/emissionFactor/Table.module.css
- src/components/emissionFactor/Table.tsx
- src/components/modals/Modal.module.css
- src/components/modals/Modal.tsx
- src/components/study/EmissionSourceFactorModal.tsx
> fix emission factor modal layout

- src/components/onboarding/Onboarding.module.css
- src/components/onboarding/OnboardingModal.tsx
- src/components/onboarding/OnboardingStep1.tsx
- src/db/organization.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/user.command.ts
> add user firstname and lastName to onboarding form

- src/components/navbar/Navbar.tsx
- src/components/team/TeamTable.tsx
- src/services/permissions/user.ts
#467 (cf comment https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/467#issuecomment-2668046957)
> gestionnaire can update organization information

- src/components/study/StudyDetailsHeader.tsx
- src/components/study/buttons/StudyPostsBlock.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/services/study.ts
> 593 retours demo

- src/scripts/ftp/importUsers.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/552
> fix user import

- src/components/team/InvitationsToValidateActions.tsx
- src/components/team/SelectRole.tsx
- src/components/team/TeamTable.tsx
- src/services/permissions/user.ts
> do not allow untrained user to switch role to other value than gestionnaire

- .env.dist
- src/app/(dashboard)/mentions-legales/page.tsx
- src/tests/end-to-end/app/legal-notices.cy.ts
> change legal mentions

- src/app/(dashboard)/facteurs-d-emission/creer/page.tsx
- src/components/pages/EmissionFactors.tsx
> do not authorize users with no organization to create emission factor

- src/components/emissionFactor/Table.tsx
- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceFactor.tsx
> add metadatalocation

- src/components/studyNavbar/StudyNavbar.module.css
- src/components/studyNavbar/StudyNavbar.tsx
- src/utils/components.tsx
> add indication on active study view

- src/i18n/en.json
- src/i18n/fr.json
> fix onboading manage role label

- src/components/study/results/Result.tsx
- src/i18n/en.json
- src/i18n/fr.json
> display unit in results graph

- src/db/study.ts
#467 : En tant qu'utilisateur CR, j'ai accès aux études publiques de mes clients, même si je ne fais pas partie des membres de l'étude
> fetch organization public studies for parent member

- src/components/onboarding/OnboardingModal.tsx
> refresh after onboarding to take new role into account in navbar

- src/components/home/UserView.tsx
- src/components/pages/Organization.tsx
- src/components/study/Studies.tsx
- src/components/study/StudiesContainer.tsx
> fix study creation url from cr client

- src/tests/end-to-end/app/study-rights.cy.ts
PR de tests pour corriger les tests cypress sur study-rights
> remove flaky cy.wait('@createStudy')

- src/css/globals.css
> apply gilroy-regular as global font

- src/components/pages/NewStudyRight.tsx
- src/components/study/rights/NewStudyContributorForm.tsx
- src/components/study/rights/NewStudyRightForm.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/permissions/check.ts
- src/services/serverFunctions/study.ts
- src/tests/end-to-end/app/home.cy.ts
> don't authorize a person to be in contributor and in team study

- src/app/(dashboard)/etudes/[id]/(contributor)/contributeur/page.tsx
- src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/saisie-des-donnees/[post]/page.tsx
- src/app/(dashboard)/etudes/[id]/(organization)/comptabilisation/saisie-des-donnees/page.tsx
- src/components/pages/NewStudyRight.tsx
- src/components/pages/StudyContribution.tsx
- src/components/pages/StudyContributor.tsx
- src/components/pages/StudyPerimeter.tsx
- src/components/pages/StudyPosts.tsx
- src/components/pages/StudyRights.tsx
- src/components/study/SubPosts.tsx
- src/components/study/rights/NewStudyRightForm.tsx
- src/services/permissions/emissionSource.ts
- src/services/permissions/study.ts
- src/utils/study.ts
#656 et [#663](https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/663)
> fix getUserRole function for cr clients studies

- src/services/permissions/emissionSource.ts
- src/services/permissions/study.ts
- src/services/serverFunctions/study.ts
> add permission for public studies

- src/components/navbar/Navbar.tsx
- src/components/pages/Public.tsx
- src/i18n/en.json
- src/i18n/fr.json
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/660
> add FAQ url to help icon

- src/components/study/StudyCard.module.css
- src/components/study/StudyCard.tsx
- src/components/study/results/ResultsContainer.module.css
#613 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/613#issuecomment-2681484395)
> fix study name layout in welcome page

- src/i18n/en.json
- src/i18n/fr.json
> mini fixes

- src/components/team/SelectRole.tsx
- src/services/serverFunctions/user.ts
#669 
Donner la possibilité aux admin de donner le rôle de gestionnaire aux membres sans formation
> allow gestionnaire role selection for untrained users

- src/scripts/ftp/importUsers.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/680
> add way of handling non french siret

- src/db/organization.ts
- src/services/serverFunctions/organization.ts
Problème : sur la modale d'onboarding l'invitation ne fonctionne que pour les utilisateurs qui n'existe pas déjà en bdd
> can invite existing users on onboarding

- src/components/modals/Modal.tsx
- src/components/study/rights/StudyLevel.tsx
- src/components/study/rights/StudyPublicStatus.tsx
> add glossary modal in study cadrage view

- src/components/base/MultiSelect.tsx
- src/components/emissionFactor/Form/EmissionFactorForm.tsx
- src/components/emissionFactor/Form/MultiplePosts.tsx
- src/components/emissionFactor/Form/Posts.module.css
- src/components/emissionFactor/Form/Posts.tsx
- src/components/emissionFactor/edit/Form.tsx
- src/components/emissionFactor/new/Form.tsx
- src/db/emissionFactors.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/posts.ts
- src/services/serverFunctions/emissionFactor.command.ts
- src/services/serverFunctions/emissionFactor.ts
- src/tests/end-to-end/app/create-emission-factor.cy.ts
- src/tests/end-to-end/app/edit-emission-factor.cy.ts
- src/utils/post.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/493
Je vous laisse me dire si tout est ok niveau ux/ui et dans le code ! N'hésitez pas si vous voulez qu'on en discute
~~J'ai juste une petite erreur Typescript dont je n'arrive pas à me débarasser si jamais quelqu'un a déjà rencontré ce problème~~
~~Dans EmissionFactorForm.tsx (ligne 77) lorsque j'appelle~~
~~` <MultiplePosts form={form} control={control} />`~~
~~form n'est pas au bon type alors que je l'ai typé exactement comme dans les autres composant ...~~
-> C'est reglé merci Louis !
> Etq 493 select multiple posts and subposts for manual fe

- src/components/organization/Sites.module.css
- src/components/organization/Sites.tsx
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/650
- removing caption
- moving title and button in div above table
- removing useless style import
- removing useless css
> fix: bug/650 moving site add button and title above table

- src/components/emissionFactor/Form/MultiplePosts.tsx
- src/components/emissionFactor/Form/Posts.module.css
- src/components/emissionFactor/Form/Posts.tsx
- src/components/emissionFactor/Table.tsx
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/493#issuecomment-2713455161
Correction sur l'affichage des erreurs c'est mieux qu'avant je pense
> fix: better display of form errors

- src/components/base/Block.tsx
- src/components/pages/StudyRights.tsx
- src/components/study/rights/StudyParams.module.css
- src/components/study/rights/StudyParams.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/services/permissions/study.ts
- src/services/serverFunctions/study.command.ts
- src/services/serverFunctions/study.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/651
Dites moi si il faut rajouter des tests, j'ai l'impression qu'il n'y en a pas pour les autres champs d'édition de cette page donc je n'y ai pas touché pour le moment
Sinon après avoir un peu retourné le problème, le plus simple pour éviter trop de refactor a été de faire une petite modal pour éditer le champs lorsqu'on clique sur le bouton d'édition, pareil dites moi si ça vous va :)
> feat: Edit study name + translations

- .env.dist
- prisma/seed/index.ts
Le seed se déclenche en staging alors qu'il ne devrait pas
Le env dist  est par défaut en environnement "development" donc se déclenche pour les tests
> Le seed ne s'active pas sur l'environnement de test

- src/db/study.ts
#818  Il y avait un bug lors de la suppression d'une étude quand celle ci est exportée au format beges
> fix study with export deletion

- src/components/pages/Public.module.css
- src/components/pages/Public.tsx
> fix login page scrollable

- src/components/pages/StudyRights.tsx
- src/components/study/rights/StudyParams.tsx
- src/components/study/rights/StudyPublicStatus.tsx
- src/components/study/rights/StudyVersions.module.css
- src/components/study/rights/StudyVersions.tsx
- src/db/emissionFactors.ts
- src/environments/base/study/StudyRights.tsx
- src/environments/core/study/DynamicStudyRights.tsx
- src/i18n/en.json
- src/i18n/fr.json
- src/services/permissions/study.ts
- src/services/serverFunctions/study.ts
#646 
Proposition de layout : 
Mise à jour :
> add study emission factor versions list

- src/components/study/results/AllResults.tsx
- src/components/study/results/ConsolatedBEGESDifference.module.css
- src/components/study/results/ConsolatedBEGESDifference.tsx
- src/i18n/en.json
- src/i18n/fr.json
> add difference explanation

- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceForm.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.ts
> duplicate emission source

- src/components/emissionFactor/Table.tsx
> move sublocation into location column

- src/components/emissionFactor/Table.tsx
- src/components/study/results/ConsolatedBEGESDifference.tsx
#699 
Le fioul est un FE qui a des sous-localisations
> change location filter to AutoComplete

- src/components/navbar/Navbar.tsx
> switch link order in navbar

- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceForm.tsx
#337 
bug car impossible de dupliquer une SE validée
> fix validated sources duplication

- prisma/migrations/20250407152300_update_import_names/migration.sql
> add migration script

- src/components/profile/Profile.tsx
#872 
J'ai changé le clic sur "Mon Profil" en clic sur le prénom nom. C'est beaucoup plus simple que de gérer le clic sur le titre du Block
> hide application version

- src/components/emissionFactor/Table.tsx
- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceContributorForm.tsx
- src/components/study/EmissionSourceFactor.tsx
- src/components/study/EmissionSourceFactorModal.tsx
- src/components/study/EmissionSourceForm.tsx
- src/components/study/SubPost.tsx
- src/services/permissions/emissionSource.ts
> allow any emission factor in emission source

- src/app/(dashboard)/etudes/[id]/(organization)/perimetre/page.tsx
> fix study organization in perimeter view

- package.json
> force node version to 22

- src/components/study/EmissionSourceFactorModal.tsx
> add manual source as initially selected in emission factors modal

- src/utils/number.ts
#798 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/798#issuecomment-2792632224)
> fix rounded number for value between 0.1 and 1

- src/services/serverFunctions/study.ts
#646 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/646#issuecomment-2793111235)
> update all emission factors

- prisma/migrations/20250327101922_add_old_bc_id_to_organizations_sites_and_studies/migration.sql
- prisma/schema/organization.prisma
- prisma/schema/study.prisma
- prisma/schema/user.prisma
- src/scripts/oldBC/transition/organizations.ts
- src/scripts/oldBC/transition/studies.ts
Introduit la colonnes old_bc_id dans les tables organizations et sites.
> Feature/add old bc id to organizations, sites and studies tables

- prisma/migrations/20250415084458_add_user_source_field/migration.sql
- prisma/schema/user.prisma
- src/scripts/ftp/userImport.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/723
> ajout de source d'utilisateurs

- src/app/(dashboard)/formation/page.tsx
- src/components/formation/EvaluationModal.tsx
- src/components/formation/Formation.tsx
- src/components/pages/Formation.tsx
Fix du lien avec typeform, il ne recevait pas les paramètres. 
J'en ai profité pour ajouter d'autres infos dont on avait besoin : le niveau, le nom de l'orga et la date
> add info + fix typeform link

- src/components/emissionFactor/Table.tsx
- src/components/study/EmissionSourceContributorForm.tsx
#798 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/798#issuecomment-2801627625)
> fix emission factor value in FE table

- src/components/study/rights/StudyVersions.tsx
- src/services/serverFunctions/study.ts
#646 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/646#issuecomment-2809090698)
> fix layout and metadata

- src/components/study/EmissionSource.module.css
- src/components/study/EmissionSource.tsx
> fix emission factor header layout

- src/components/base/Toast.tsx
- src/components/form/Autocomplete.tsx
- src/components/form/Checkbox.tsx
- src/components/form/DatePicker.tsx
- src/components/form/Form.module.css
- src/components/form/QualitySelect.tsx
- src/components/form/Radio.tsx
- src/components/form/Select.tsx
- src/components/form/TextField.tsx
- src/components/modals/DeletionModal.tsx
- src/components/onboarding/Onboarding.module.css
- src/components/onboarding/OnboardingModal.tsx
- src/components/onboarding/OnboardingStep1.tsx
- src/components/onboarding/OnboardingStep2.tsx
- src/components/organization/Sites.tsx
- src/components/profile/Profile.module.css
- src/components/profile/Profile.tsx
- src/components/study/rights/StudyParams.tsx
- src/css/var.css
- src/environments/base/organization/Sites.module.css
- src/environments/base/organization/Sites.tsx
- src/tests/end-to-end/app/team.cy.ts
#695 
À tester sur toute l'appli, il peut y avoir des changements dans le layout
> add static error message space

- src/components/study/rights/StudyParams.tsx
> Retirer la selection de l'unité, la maturité, la visibilité et version

- package.json
> re-configure turbopack

- src/components/auth/ActivationForm.tsx
- src/components/auth/LoginForm.tsx
- src/components/auth/NewPasswordForm.tsx
- src/components/auth/ResetForm.tsx
- src/components/onboarding/OnboardingModal.tsx
- src/components/study/EmissionSource.tsx
- src/i18n/en.json
- src/i18n/fr.json
#921 
J'ai supprimé le isValid dans la plupart des formulaires car c'est déjà géré par le handleSubmit (on ne rentre pas dans le onSubmit si le formulaire n'est pas valide). Il reste quelques occurrences sur des cas particuliers (il faut supprimer des valeurs du form, c'est un update plutôt que submit, ...)
> harmonize form management

- src/db/emissionSource.ts
- src/db/organizationImport.ts
- src/db/user.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/923
> remove updated at

- src/app/(dashboard)/etudes/[id]/(organization)/page.tsx
- src/components/pages/Study.tsx
- src/components/study/StudyDetails.tsx
- src/components/study/results/AllResults.tsx
- src/components/study/results/consolidated/ConsolidatedResults.tsx
> use validated only user params in study results graph

- src/components/auth/NewPasswordForm.tsx
- src/components/auth/ResetForm.tsx
#908 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/908#issuecomment-2857658252)
> send lowercase email in reset password forms

- src/services/permissions/formations.test.ts
- src/services/permissions/formations.ts
- src/services/serverFunctions/deactivableFeatures.ts
Problème d'accès à l'onglet formation. À merger et déployer au plus vite !
> fix server-based function access

- src/services/permissions/emissionSource.test.ts
- src/services/permissions/emissionSource.ts
- src/tests/utils/models/emissionSource.ts
- src/tests/utils/models/organization.ts
- src/tests/utils/models/study.ts
Je n'ai finalisé qu'une seule méthode pour le moment. J'y vais petit à petit pour être sûre de pas laisser en plan du code si pas le temps demain de coder ^^
> end unit test emission source permissoin hasStudyBasicRights

- src/components/navbar/Navbar.tsx
> remove methodo link when user has an organization card

- src/components/form/DatePicker.tsx
> fix date picker background color

- src/components/study/results/ConsolatedBEGESDifference.tsx
- src/utils/number.ts
#1047 
Je n'ai pas réussi à reproduire l'erreur en local (même si le fix est assez évident), à tester avec précaution donc
> format values to fix differences between beges and consolated

- src/components/auth/LoginForm.tsx
> add email lowercase on login

- src/services/auth.ts
Empêche les users sans orga de rester bloqué au login
> fix: allowing user to login without organizationVersion

- src/db/organization.ts
- src/services/serverFunctions/study.ts
#1094 
cherry-pick du commit réalisé dans le hotfix https://github.com/ABC-TransitionBasCarbone/bilan-carbone/pull/1097
> fix user source on creation

- src/app/layout.tsx
- src/components/pages/NewStudy.tsx
- src/environments/cut/study/new/Form.tsx
- src/i18n/request.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1117
> if cut local fr mandatory

- src/components/study/StudyDetailsHeader.tsx
- src/components/study/results/AllResults.tsx
- src/components/study/site/SelectStudySite.tsx
- src/environments/cut/study/results/AllResults.tsx
- src/services/serverFunctions/study.ts
- src/utils/study.ts
#1079 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1079#issuecomment-2957891980)
> fix site selector on study home page

- src/components/pages/SelectAccount.tsx
- src/environments/core/EnvironmentInitializer.module.css
- src/environments/core/EnvironmentInitializer.tsx
- src/store/AppEnvironment.ts
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1142
Normalement ça charge un peu plus vite on verra ce que ça donne sur staging et du coup j'ai rajouté un Loader sans m'attarder sur le front j'attendais votre avis est-ce que je change la couleur du fond et du cercle ?
https://github.com/user-attachments/assets/476ef397-b35a-4376-afd6-27f387fede4e
> fix: better chargning between env translations

- src/components/study/EmissionSourceFactor.tsx
#1076 (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1076#issuecomment-2957953824)
> add warning when open emission factor suggestion dropdown

- src/components/emissionFactor/Form/MultiplePosts.tsx
- src/components/emissionFactor/Form/Posts.tsx
- src/components/emissionFactor/Form/SubPostSelector.tsx
- src/components/study/rights/StudyContributorsTable.module.css
- src/components/study/rights/StudyContributorsTable.tsx
- src/db/study.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/serverFunctions/study.ts
> feat: new all posts and all subposts options in contributor form + contributor table grouped by email

- src/components/study/site/SelectStudySite.tsx
#1079  (cf https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1079#issuecomment-2963262293)
> disable study site selector when only one site

- prisma/seed/index.ts
- src/app/(dashboard)/page.tsx
- src/components/home/UserView.tsx
- src/constants/environments.ts
- src/constants/users.ts
link to #1193 
Idem que pour la checklist j'ai prépraré pour intégrer facilement d'autres env
> no onboarding for cut users

- prisma/seed/index.ts
- src/app/(dashboard)/layout.tsx
- src/app/layout.tsx
- src/constants/environments.ts
- src/constants/userCheckedSteps.ts
- src/db/user.ts
- src/services/serverFunctions/user.ts
link to #1194
J'ai préparer le fait que TILT ou un prochain environement aurait peut être la checklist. Du coup il suffira d'ajotuer les environnement qui y ont accès dans le tableau correspondant
> hide checklist for non authorized env

- src/components/study/rights/StudyContributorsTable.tsx
- src/i18n/en.json
- src/i18n/fr.json
> fix: keep parent column text fixed + singular/plural string handling

- prisma/schema/migrations/20250620083102_move_cinema_info_in_site/migration.sql
- prisma/schema/study.prisma
- src/db/study.ts
- src/environments/core/study/DynamicStudyRights.tsx
- src/environments/cut/study/StudyRights.tsx
- src/environments/cut/study/new/Form.tsx
- src/services/hours.ts
- src/services/serverFunctions/study.command.ts
- src/services/serverFunctions/study.ts
- src/tests/utils/models/study.ts
link to #1200 
@RomainCrevecoeur j'ai été obligé de mettre une gestion du loading dans la page quand on change de site. Si on ne veut pas ca, il faut faire une gestion de mise à jour en local des changements fait par l'utilisateur. Dis moi si ca te convient ou si je dois gérer autrement.
> 1200 cut move general data in site

- src/app/(dashboard)/layout.tsx
- src/components/checklist/ChecklistButton.tsx
- src/components/checklist/ChecklistDrawer.tsx
- src/services/checklist.ts
- src/services/serverFunctions/user.ts
> remove create study check step when user is not trained

- src/i18n/fr-cut.json
- src/i18n/fr.json
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1019#issuecomment-3004279325
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1254#issuecomment-3004252189
Petite PR suite aux retours de Gabriel
C'est réglé pour le wording ici
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1019#issuecomment-3004279325
Pour le 2ème commentaire j'ai fait les changements dans le csv et j'ai mis une réponse pour le reste des remarques :
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1254#issuecomment-3008513992
> refactor: wording in results for cut

- .github/workflows/ci.yml
- cypress.config.ts
#1288
Étapes de la CI : 
1. En parallèle : Lint et tsc, unit tests, build et database setup (ces actions ne sont pas interdépendantes)
2. Une fois toutes les étapes 1 faites, en parallèle : e2e tests et lighthouse
> Découpage et parallélisation des étapes de la CI

- src/db/question.ts
- src/services/results/consolidated.ts
- src/services/serverFunctions/question.ts
link to #1335 
@RomainCrevecoeur j'ai pas réparé les seeds car trop galère parce qu'il nous fait la base empreinte 23.5. Donc il faut forcément créer une étude pour tester la réponse au question et l'impact sur les résultats
> fix get answers for result

- src/db/study.ts
- src/services/serverFunctions/study.ts
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1354
> Créer des FE versions uniquement pour l'environnement en cours

- src/db/emissionFactors.ts
- src/services/serverFunctions/question.ts
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1370
> fix error findEmissionFactorByImportedId

- src/components/organization/Sites.tsx
- src/components/organization/edit/EditOrganizationForm.tsx
- src/components/pages/EditOrganization.tsx
- src/components/study/new/Form.tsx
- src/components/study/organization/Select.tsx
- src/environments/cut/organization/Sites.tsx
- src/environments/cut/study/new/Form.tsx
- src/i18n/en.json
- src/i18n/fr-cut.json
- src/i18n/fr.json
> #1359 - ETQ Utilisateur,  j'ai une page "Mes cinémas" légèrement modifiée

- src/components/dynamic-form/inputFields/TableInput.tsx
- src/environments/cut/study/DynamicSubPostForm.tsx
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1254
> add current study year to question

- src/components/dynamic-form/FieldComponent.tsx
- src/components/dynamic-form/inputFields/SelectInput.tsx
- src/components/dynamic-form/inputFields/TableInput.tsx
- src/components/dynamic-form/inputFields/TextUnitInput.tsx
- src/components/dynamic-form/inputFields/YearPickerInput.tsx
- src/constants/emissionFactorMap.ts
- src/db/question.ts
- src/services/serverFunctions/question.ts
- src/utils/tableEmissionCalculations.ts
TODO:
- source qui ne se supprime pas malgré des champs invalides ou manquants si plusieurs sources correspondent à une même ligne => ex: Décrivez les différentes salles du cinéma > mettre toutes les infos correctes > vérifier que les sources d'émissions sont correctes > mettre une année d'acquisition dans le futur ou vider une quantité > la source correspondante n'est pas supprimée
> feat: table input calculations and emission factor map updates

- src/services/serverFunctions/question.ts
> fix bug on depreciation period

- src/db/question.ts
- src/scripts/cut/question/add.ts
> change create to upsert questions

- src/components/dynamic-form/inputFields/TableInput.tsx
lié à #1480 
@alexphiev est-ce que tu sias pourquoi on avait cette condition? A priori le reset des tableaux fonctionnaient il y a encore quelques jours, est-ce que tu sais ce qui a pu changé récemment qui aurait pu causer ce problème ? J'ai l'impression que la condition existe depuis assez longtemps donc je serais étonnée que ce soit ca.
> update value if empty string

- src/components/study/card/StudyPostsCard.tsx
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1511
> Retirer le role dans la carte lors du remplissage des questions

- src/constants/emissionFactorMap.ts
- src/utils/tableEmissionCalculations.ts
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1538
> feat(question): add new element in question

- src/constants/emissionFactorMap.ts
- src/services/posts.ts
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1499
Attention, cela nécessite un nouvel import des questions (car changement dans possibleAswers).
> fix: nom simplifié fe transport + fix oublie ticket multiples fixes

- src/i18n/fr-cut.json
- src/i18n/fr.json
- src/tests/end-to-end/app/create-emission-source.cy.ts
- src/tests/end-to-end/app/onboarding.cy.ts
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/934
> écriture inclusive et corrections mineures

- src/app/preview/etudes/[id]/PDFSummary.tsx
- src/components/emissionFactor/Table.tsx
- src/components/study/EmissionSource.tsx
- src/components/study/EmissionSourceContributorForm.tsx
- src/components/study/EmissionSourceFactor.tsx
- src/components/study/EmissionSourceForm.tsx
- src/components/study/buttons/StudyPostsBlock.tsx
- src/components/study/infography/AllPostsInfographyContainer.tsx
- src/components/study/results/ConsolatedBEGESDifference.tsx
- src/components/study/results/StudyResultsContainerSummary.tsx
- src/components/study/results/consolidated/ConsolidatedResultsTable.tsx
- src/hooks/useChartComputations.ts
- src/services/emissionSource.ts
- src/services/permissions/environment.ts
- src/services/results/consolidated.ts
- src/services/study.ts
- src/services/uncertainty.ts
- src/utils/emissionFactors.ts
Les émissions liées aux déchets ont le FE fixe avec valeur 41 mais ça ne doit pas être appliqué à CUT.
> fix: waste emission not hardcoded for CUT, only BC+

- src/services/importEmissionFactor/import.ts
En plus de la commande si-dessous, j'ai modifié la méthode `addSourceToStudies` qui produit l'erreur lors d'un import avec script des FE. Ça n'affectait pas le flow normal de création d'une étude mais si on utilise le script d'import ça ajoutait aussi les FE CUT aux études BC+ si j'ai bien compris.
SQL pour nettoyer les  FE CUT dans des études non CUT.
```sql
DELETE FROM public.study_emission_factor_versions
WHERE id IN (
SELECT sefv.id
FROM public.study_emission_factor_versions sefv
JOIN public.studies s ON s.id = sefv.study_id
JOIN public.accounts a ON a.id = s.created_by_account_id
WHERE sefv.source = 'CUT'
AND a.environment != 'CUT'
);
```
> fix: add CUT check for seed and import script

- src/i18n/fr.json
https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1590
> fix: inclusive writing

- prisma/schema/migrations/20250819142801_remove_old_tag/migration.sql
- prisma/schema/study.prisma
- src/app/(public)/preview/etudes/[id]/ChartsPage.tsx
- src/components/base/Title.tsx
- src/components/study/charts/PieChart.tsx
- src/components/study/perimeter/EmissionSourceTags.tsx
- src/components/study/results/AllResults.tsx
- src/components/study/results/Filters.tsx
- src/components/study/results/ResultsTableAndGraphs.tsx
- src/components/study/results/StudyResultsContainerSummary.tsx
- src/components/study/results/beges/BegesResultsTable.tsx
- src/components/study/results/consolidated/CarbonIntensities.tsx
- src/components/study/results/consolidated/EmissionsAnalysis.tsx
- src/components/study/results/consolidated/TotalCarbonBeges.tsx
- src/css/globals.css
- src/css/var.css
- src/environments/cut/study/results/AllResults.tsx
- src/hooks/useChartComputations.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/services/emissionSource.ts
- src/services/results/consolidated.test.ts
- src/services/results/consolidated.ts
- src/services/results/utils.ts
- src/services/study.ts
- src/tests/utils/models/emissionSource.ts
- src/tests/utils/models/study.ts
- src/utils/charts.test.ts
- src/utils/charts.ts
- src/utils/post.ts
> 1598 tag graph

- src/components/base/Title.tsx
- src/components/study/perimeter/EmissionSourceTags.tsx
- src/components/study/results/ResultsContainer.module.css
- src/components/study/results/consolidated/TotalCarbonBeges.tsx
- src/constants/emissionSourceTags.ts
- src/css/var.css
> multiple fixes

- src/i18n/en-tilt.json
- src/i18n/translations.test.ts
> add tilt trad

- src/i18n/en-tilt.json
- src/i18n/en.json
- src/i18n/fr-tilt.json
- src/i18n/fr.json
- src/services/permissions/environment.ts
> 1637 add bc

- package.json
- prisma/seed/index.ts
- src/components/study/EmissionSourceForm.tsx
- src/components/study/new/Form.tsx
- src/db/emissionSource.ts
- src/db/study.ts
- src/services/serverFunctions/study.test.ts
- src/services/serverFunctions/study.ts
- src/tests/end-to-end/app/create-emission-source.cy.ts
> 1644 fix duplication

- src/components/study/EmissionSource.module.css
- src/components/study/EmissionSourceForm.tsx
> fix tag size in emission source form

- src/components/dynamic-form/QuestionContainer.module.css
- src/components/dynamic-form/QuestionContainer.tsx
- src/constants/emissionFactorMap.ts
- src/environments/base/theme/theme.ts
- src/environments/cut/theme/theme.ts
- src/i18n/en.json
- src/i18n/fr.json
⚠️ Rappel : Réimporter les questions du GSheet pour avoir le changement de label
> feat: added hepler text in questions hardcoded for now

- .env.dist
- src/components/pages/Ressources.tsx
- src/components/ressources/RessourceLinks.tsx
- src/i18n/en.json
- src/i18n/fr-cut.json
- src/i18n/fr.json
- src/lib/environment.ts
- src/services/email/email.ts
- src/types/email.ts
⚠️ À faire pour la MEP
Ajouter les variables d'environnement suivantes :
* SUPPORT_EMAIL
* CONTACT_FORM_URL
* CUT_MAIL_USER
* CUT_MAIL_PASSWORD
* CUT_MAIL_HOST
* CUT_SUPPORT_EMAIL
* CUT_CONTACT_FORM_URL
> feat: SMTP config CUT + env variables config

- src/constants/emissionFactorMap.ts
- src/utils/tableEmissionCalculations.ts
lié à #1715
Pour le moment, mes questions sont dans la copie de l'excel (onglet sur le meme excel) parce que mon autre pr n'a pas été fusionnée du coup je ne pouvais pas utiliserle meme. Il faudra que je les fusionner avant la mep. 
Pour le moment j'ai pas fait de rattrapage. Je vais voir avec Romain, je crois qu'à un moment on avait pu supprimer les données des étude
RESTE A faire : (je remettrais le ticket en todo) : faire un rattrapage si ce n'est pas trop long pour supprimer les réponses, ou encore mieux, les déplacer au bon endroit.
> split question in two

- src/environments/cut/home/UserView.tsx
- src/i18n/fr-cut.json
> change homepage

- src/components/study/charts/BarChart.tsx
- src/i18n/fr.json
- src/utils/charts.ts
J'ai caché 0 comme valeur du graph en barre pour éviter ça :
> fix: check if subpost theme exists before selecting color + hide value 0 in bar chart

- .github/ISSUE_TEMPLATE/ticket-de-fonctionnalité.md
- .github/pull_request_template.md
PR liée au(x) ticket(s) : #1791
> first proposition

- src/i18n/fr-cut.json
PR liée au(x) ticket(s) : #1807
> change wording saisie des données cut

- prisma/schema/migrations/20250924101507_add_entree2024/migration.sql
- prisma/schema/organization.prisma
- src/db/organization.ts
- src/db/study.ts
- src/scripts/cut/cnc/add.ts
- src/scripts/fillStudySiteDataFromCNC.ts
- src/utils/cnc.ts
PR liée au(x) ticket(s) :
- https://github.com/ABC-TransitionBasCarbone/bilan-carbone/issues/1815
> handle entree2024 variable in cnc csv

- src/app/(dashboard)/layout.module.css
- src/app/(dashboard)/layout.tsx
- src/components/studyNavbar/StudyNavbar.module.css
- src/css/variables.css
> fix: adapt height to with or without orgaCard + clean unused old code

- package.json
- src/components/modals/DuplicateStudyModal.tsx
- src/components/modals/Modal.tsx
- src/components/pages/NewStudy.tsx
- src/components/study/new/BegesDeactivationWarningModal.tsx
- src/components/study/new/ExportCheckbox.test.tsx
- src/components/study/new/ExportCheckbox.tsx
- src/components/study/perimeter/ControlModeChangeWarningModal.tsx
- src/environments/base/study/new/Form.tsx
- src/hooks/useDuplicateStudy.ts
- src/i18n/en.json
- src/i18n/fr.json
- src/types/jest-dom.d.ts
- yarn.lock
> feat: add new beges deactivation warning + fix beges activation warning behavior + unit tests for export checkbox component

- src/services/study.ts
#1799 
PR liée au(x) ticket(s) :
> configure tilt to bc study copy

- src/services/importEmissionFactor/posts.config.ts
> Changement de sous-postes pour les FE concernés

- src/components/pages/StudyPostsPage.tsx
- src/components/study/results/AllResults.tsx
> fix: give the diff modal the result with dependance

- src/i18n/fr.json
> Nourriture, repas, boissons
